FROM ubuntu:18.04
ENV OS ubuntu
WORKDIR /usr/repo
RUN apt-get update -y && apt-get install wget maven git -y \
    && apt-get autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY "build-ambari.sh" /usr/repo/
CMD ["/usr/repo/build-ambari.sh"]
