FROM ubuntu:18.04
ENV OS ubuntu
WORKDIR /usr/repo
RUN apt-get update -y && apt-get install wget maven git -y \
    && apt-get autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN groupadd -r -g 1001 ambari && useradd -r -g ambari -u 1001 ambari && chown ambari:ambari /usr/repo
USER ambari
COPY "build-ambari.sh" /usr/repo/
CMD ["/usr/repo/build-ambari.sh"]
